name: Publish Next

on:
  release:
    types: [prereleased]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm unpublish @themost/oracle@next
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
